import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        
        h2{
          font-size: 32px;
        };
        h3{
          font-size: 28px;
        }
        `}

      </style>
      <Head>
        <title>hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 


      <main className={styles.main}>
        <h1 className={styles.title}>hunting coder</h1>
<div className={styles.imaheWrap}>
<Image className={styles.myImg} src="/home.avif" width={237} height={158}  alt="coder posts"/>

</div>
        <p className={styles.description}>
          A blog for Hunting Coders by Hunting Coder
        </p>

<div>

        <div className="blogs">
        <h2>Populer Blogs</h2>
          <div className="blogItem">
            <h3> How to learn JavaScript in 2022</h3>
            <p> JavaScript is a language use to design a logic from web</p>
          </div>
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3> How to learn JavaScript in 2022</h3>
            <p> JavaScript is a language use to design a logic from web</p>
          </div>
        </div>
        <div className="blogs">
          <div className="blogItem">
            <h3> How to learn JavaScript in 2022</h3>
            <p> JavaScript is a language use to design a logic from web</p>
          </div>
        </div>
</div>
      </main>
    </div>
  );
}
